seed: 42
accelerator: "cuda"
default_root_dir: "results"

tiling:
  tile_size: [128, 128]
  stride: 128

normalization_stage: image # on what level we normalize, options: [tile, image, none]
thresholding:
  method: F1AdaptiveThreshold # refer to documentation for thresholding methods
  stage: image # stage at which we apply threshold, options: [tile, image]

data:
  class_path: anomalib.data.MVTec
  init_args:
    root: ./datasets/MVTec
    category: bottle
    train_batch_size: 32
    eval_batch_size: 32
    num_workers: 8
    task: segmentation
    transform: null
    train_transform: null
    eval_transform: null
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    image_size: [256, 256]

SeamSmoothing:
  apply: True # if this is applied, area around tile seams are is smoothed
  sigma: 2 # sigma of gaussian filter used to smooth this area
  width: 0.1 # width factor, multiplied by tile dimension gives the region width around seam which will be smoothed

TrainModels:
  model:
    class_path: Padim

  metrics:
    pixel: AUROC
    image: AUROC
